kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
archiveSize: 10
mirror:
  platform:
    channels:
    - name: stable-4.19
      type: ocp
      minVersion: 4.19.40
      maxVersion: 4.19.40
    graph: false