kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
archiveSize: 10
storageConfig:
  local:
    path: /mnt/mirror-data/4.20-openshift-ai-p1-metadata
mirror:
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.20
    targetCatalog: redhat/redhat-oai-operator-index-p1
    targetTag: v4.20-1
    packages:
    - name: rhods-operator
      defaultChannel: stable-3.x
      channels:
      - name: stable-3.x
        minVersion: 3.3.2
        maxVersion: 3.3.2
    - name: servicemeshoperator3
      defaultChannel: stable
      channels:
      - name: stable
        minVersion: 3.3.2
        maxVersion: 3.3.2
    - name: rhcl-operator
      defaultChannel: stable
      channels:
      - name: stable
        minVersion: "1.3.2"
        maxVersion: "1.3.2"
    - name: kueue-operator
      defaultChannel: stable-v1.3
      channels:
      - name: stable-v1.3
        minVersion: "1.3.1"
        maxVersion: "1.3.1"
    - name: job-set
      defaultChannel: stable-v1.0
      channels:
      - name: stable-v1.0
        minVersion: 1.0.0
        maxVersion: 1.0.0
    - name: openshift-custom-metrics-autoscaler-operator
      defaultChannel: stable
      channels:
      - name: stable
        minVersion: "2.18.1-2"
        maxVersion: "2.18.1-2"
    - name: openshift-cert-manager-operator
      defaultChannel: stable-v1
      channels:
      - name: stable-v1
        minVersion: 1.19.0
        maxVersion: 1.19.0
    - name: leader-worker-set
      defaultChannel: stable-v1.0
      channels:
      - name: stable-v1.0
